name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 7 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync Fork
        uses: repo-sync/github-sync@v2
        with:
          source_repo: 'runelite/runelite'
          source_branch: 'master'
          destination_branch: 'master'
          github_token: ${{ secrets.GITHUB_TOKEN }}